### ISSUE TITLE
from: darwinia release binary  

### ISSUE THREAD

**Issue by PedroJuan91** [darwinia-network/darwinia#528] opened 2020-09-14 04:35 UTC
I use the binary release and I don't know if it is really a bug or just misconfigure. 
please delete this issue if not a bug. 
thanks.. 

issue notes from console

```
====================

    Version: 0.6.10-93dffe6-x86_64-linux-gnu

      0: sp_panic_handler::set::{{closure}}
      1: std::panicking::rust_panic_with_hook
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: darwinia_cli::command::<impl sc_cli::SubstrateCli for darwinia_cli::cli::Cli>::load_spec
   6: sc_cli::config::CliConfiguration::create_configuration
   7: sc_cli::runner::Runner<C>::new
   8: darwinia_cli::Configuration::create_runner
   9: darwinia_cli::command::run
  10: darwinia::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/std/src/panic.rs:382
      std::rt::lang_start_internal
             at /rustc/5099914a16a215794ad243df0cc7a05d91d168e0/library/std/src/rt.rs:51
  14: main
  15: __libc_start_main
  16: <unknown>


Thread 'main' panicked at 'not implemented', cli/src/command.rs:83

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new
```

**Comment by AurevoirXavier** [comment] 2020-09-14 04:37
Duplicate of #493

**Closed by AurevoirXavier** 2020-09-14 04:37 UTC
